version: '2'

networks:
  limnet:

services:

  peer0.limnet.io:
    container_name: peer0.limnet.io
    image: lekssays/declimnet:latest
    environment:
    - DISCOVERY_ADDRESS=peer0.limnet.io
    - DISCOVERY_PORT=1337
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../autopeering:/autopeering
    - ../gossip:/gossip
    networks:
    - limnet

  peer1.limnet.io:
    container_name: peer1.limnet.io
    image: lekssays/declimnet:latest
    environment:
    - DISCOVERY_ADDRESS=peer1.limnet.io
    - DISCOVERY_PORT=1337
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../autopeering:/autopeering
    - ../gossip:/gossip
    networks:
    - limnet

