version: '2'

networks:
  basic:

services:

  178.22.11.09_peer.limnet.io:
    container_name: 178.22.11.09_peer.limnet.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=178.22.11.09_peer.limnet.io
    - CORE_PEER_IP_ADDRESS=178.22.11.09
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    networks:
    - basic

  33.26.189.20_peer.limnet.io:
    container_name: 33.26.189.20_peer.limnet.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=33.26.189.20_peer.limnet.io
    - CORE_PEER_IP_ADDRESS=33.26.189.20
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    networks:
    - basic

  23.173.32.12_peer.limnet.io:
    container_name: 23.173.32.12_peer.limnet.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=23.173.32.12_peer.limnet.io
    - CORE_PEER_IP_ADDRESS=23.173.32.12
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    networks:
    - basic

  99.21.221.11_peer.limnet.io:
    container_name: 99.21.221.11_peer.limnet.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=99.21.221.11_peer.limnet.io
    - CORE_PEER_IP_ADDRESS=99.21.221.11
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    networks:
    - basic

  239.33.21.78_peer.limnet.io:
    container_name: 239.33.21.78_peer.limnet.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=239.33.21.78_peer.limnet.io
    - CORE_PEER_IP_ADDRESS=239.33.21.78
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    networks:
    - basic

